version: '3.8'

services:
  springboot-app:
    image: alquilerplataforma:latest
    container_name: springboot-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Mapea el puerto 8080 del contenedor al puerto 8080 del host
    volumes:
      - ./src/main:/app/src/main  # Mapea tu código fuente (cualquier cambio en el código se reflejará sin necesidad de reconstruir)
      - ./target:/app/target  # Mapea la carpeta target para guardar las compilaciones
    environment:
      - SPRING_PROFILES_ACTIVE=dev  # Puedes configurar perfiles de Spring para desarrollo
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/alquiler_db  # Conexión con la base de datos
      - SPRING_DATASOURCE_USERNAME=root  # Usuario de la base de datos
      - SPRING_DATASOURCE_PASSWORD=rootpassword  # Contraseña de la base de datos
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update  # Configuración para que Hibernate actualice la base de datos automáticamente
    depends_on:
      - mysql-db  # Asegura que MySQL esté listo antes de arrancar el proyecto

  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Establece la contraseña de root de MySQL
      MYSQL_DATABASE: alquiler_db  # El nombre de tu base de datos
    ports:
      - "3306:3306"  # Mapea el puerto de MySQL
    volumes:
      - mysql-data:/var/lib/mysql  # Este volumen persiste la base de datos

volumes:
  mysql-data:  # Volumen persistente de la base de datos para que no se borre al reiniciar
